JarvisIsReady1=['Hey, there!','Hi','Hello']
JarvisIsReady=["Jarvis here","Hey, What's up?","Hey, I'm listening","Yup, I'm on"]
YouWish=['jarvis','hey','hi','hello','jarvis?']
JarvisIsDoing=['Not much, what about you?','Just chilling, u?','Listening to music, u?']
JarvisIsDoing2=['Not much','Just chilling','Listening to music']
#find an alternative for SID2, like adding 'wbu?' seperately
URDoing=['nmu?','what about you?','u?','not much, u?']#only 'u?' has relevance
Wassup=['wassup',"what's up","what's up?",'wassup?','sup?','wyd?']
HowUDoin=['how are you?', 'how r u?','hw r u?','how are you','how r u']
Fine=['Fine, what about u?',"I'm fine, u?","I'm good, u?"]  
NotUnderstood=['I dont know how to respond to that','Sorry, I didnt get you','Sorry, can you repeat?'] 
Complement=[] #write code
Exclamation=['nice','cool',"that's awesome",'good','great']
Exclamtion2=['Oh!, you must go to hospital','Oh no!, should I help?','Oh!, do you need help?'] #modify
Thanks=['Thanks','Thank You','Gracias','thanks','thankyou','thank','gracias'] #write code
Welcome=['You are welcome!','Anytime','No Problem']
Apology=[] #write code
Bad=["sick",'feeling','injured',"not",'got','hurt','broke','broken','hit','me','t','is','s','help','need','m','am'] #test code
Bad2=['fever','cold','pain','fainted','bit','bitten','hit','hospital','hospitals'] #test code
Bad3=['die','dead','coma','cancer','died','drunk','wasted'] #test code
ByeY=['bye','goodbye','adios']
ByeS=['Goodbye','OK, see you later','Untill next time..']
Yeah=['yeah','yes','yup','yep']
ThoughtSo=['Thought so','I thought so',"That's what I thought"]
Laugh=['haha','lol','hehe','lmao','rofl','hahaha']
LaughW=['Did I make you laugh?','Haha','Was it funny?']
Okay=['ok','okay','okey dokey']
Oh=['oh','oh!, wait..what?','omg','oh my god','shit']
WhatHap=['What happened?','Did anything happen?','Anything happened?']
Time=['time','clock'] #Time
lookUp=[['look','search','show','find','go','up'],['up','for','me','to','look']]
question=['what','why','who','how','which','when','download','where']
pronounce=['pronounce','say','speak']
fWord=['fuck','fucking','fucked','shit','motherfucking','motherfucker','dick','pussy','cunt','douchebag']
modest=[['you','are','u'],['i','me','we'],['your','ur']]
love=['love','like','am'] #modify
great=['great','awesome','wonderful','amazing']#could be used in multiple places
no=['no','nope','nothing','not']
food=[['burger','pizza','hamburger','starbucks'],['hungry']]
foodJ=['Bon Apetit!','Hungry, huh?','I sense you are hungry']
webResults=["Here's what I found on the web","Here are some matches","Take a look"] 
listen=["Listen carefully, I won't repeat","Here, listen","It is how it should be said"]
mindLanguage=["Your language!","Oh!","But, that's not the best way to say that"]
Connect=[['their','its','it','there','that'],['his','he'],['her','she']]
iPhone=['iphone','remote','away']
backtoLap=[['normal','to','turn','in','am'],['laptop','mac','macbook','mode','off','back']]
backtoLapJ=["I'll miss you, iPhone","Okay, Welcome back","I'm back"]
suggest1=['better']
suggest2=['rather','better']
Help=["need","help","want","me"]
Help1J=["I'm always there to help you, just tell me","What is it?","What happened?"]
Help2J=["This may help","This may help you","Ok, This may help"] #add
doDid=[["do","did","have","is","are","can",'were','s','re'],['is','are','was','were','s','re'],["can"]]
specKey=[['age','old']]
specAns=[['years','old']]
lastAnswer=['','','']
ikr=['I know, right?',"that's true","I agree"]
learned=["Oh!, I'm sorry, I understand now","Sorry, I can understand now.","I'm sorry, I won't repeat that"]
sorry=["I'm sorry","I'm really sorry","I'm sorry"]
lights=['lights','on','off']
read_book=['read']
    
